import { useEffect, useState } from 'react';
import { submitComplaint } from '../api/complaintsApi.js';
import { getDepartments } from '../api/complaintsApi.js';
import { useLanguage } from '../i18n/I18n.jsx';
export default function ComplaintForm({ onSubmitted }) {
  const { t } = useLanguage();
  const [departments, setDepartments] = useState([]); const [form, setForm] = useState({ title: '', description: '', lat: '', lng: '', address: '', department_id: '', preferred_language: localStorage.getItem('language') || 'en' }); const [media, setMedia] = useState(null); const [message, setMessage] = useState('');
  useEffect(() => { getDepartments().then(({ data }) => { setDepartments(data); if (data[0]) setForm((current) => ({ ...current, department_id: String(data[0].id) })); }).catch(() => {}); }, []);
  const locate = () => navigator.geolocation?.getCurrentPosition(({ coords }) => setForm((current) => ({ ...current, lat: coords.latitude, lng: coords.longitude })));
  const submit = async (event) => { event.preventDefault(); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); if (media) data.append('media', media); const result = await submitComplaint(data, localStorage.getItem('citizenToken')); setMessage(`Report #${result.data.complaint.id} submitted`); onSubmitted?.(); } catch (error) { setMessage(error.response?.data?.error || 'Unable to submit report'); } };
  return <form className="panel form" onSubmit={submit}><div className="eyebrow">{t('citizenAccount').toUpperCase()}</div><h2>{t('reportTitle')}</h2><label>Complaint title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Department<select required value={form.department_id} onChange={(e) => setForm({ ...form, department_id: e.target.value })}>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select></label><label>Preferred language<select value={form.preferred_language} onChange={(e) => setForm({ ...form, preferred_language: e.target.value })}><option value="en">English</option><option value="kn">ಕನ್ನಡ</option><option value="hi">हिन्दी</option></select></label><label>{t('description')}<textarea required placeholder={t('description')} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="row"><label>{t('latitude')}<input placeholder={t('latitude')} value={form.lat} onChange={(e) => setForm({ ...form, lat: e.target.value })} required /></label><label>{t('longitude')}<input placeholder={t('longitude')} value={form.lng} onChange={(e) => setForm({ ...form, lng: e.target.value })} required /></label><button type="button" onClick={locate}>{t('detectLocation')}</button></div><label>{t('address')}<input placeholder={t('address')} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><label>{t('photo')}<input type="file" accept="image/*,video/*" onChange={(e) => setMedia(e.target.files[0])} /></label><button className="primary">{t('submit')}</button>{message && <p className="message">{message}</p>}</form>;
}