import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Link } from 'react-router-dom';
import { requestOfficerOtp, verifyOfficerOtp } from '../api/complaintsApi.js';
import { useLanguage } from '../i18n/I18n.jsx';

export default function OfficerLogin() {
  const { t } = useLanguage(); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [otpRequested, setOtpRequested] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { if (!otpRequested) { const response = await requestOfficerOtp(phone); setMessage(response.data.message); setOtpRequested(true); } else { const response = await verifyOfficerOtp({ phone, otp }); localStorage.setItem('officerToken', response.data.token); localStorage.setItem('officerProfile', JSON.stringify(response.data.officer)); navigate('/officer-dashboard'); } } catch (requestError) { setError(requestError.response?.data?.error || t('invalidCredentials')); } };
  return <main className="auth-page"><section className="auth-card"><div className="section-kicker">{t('officer').toUpperCase()}</div><h1>{t('officerLogin')}</h1><p>{otpRequested ? 'Enter the 6-digit OTP logged by the backend.' : 'Enter your registered phone number to receive an OTP.'}</p><form onSubmit={submit}><label>Registered phone number<input type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} required /></label>{otpRequested && <label>6-digit OTP<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={otp} onChange={(event) => setOtp(event.target.value)} required /></label>}{error && <p className="error-message">{error}</p>}{message && <p className="message">{message}</p>}<button className="button primary-button">{otpRequested ? 'Verify OTP' : 'Send OTP'}</button></form>{otpRequested && <button type="button" className="text-button" onClick={() => { setOtpRequested(false); setOtp(''); setMessage(''); }}>Use a different phone</button>}<p className="auth-switch">Need an account? <Link to="/officer-register">Register as an officer</Link></p></section></main>;
}