import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getDepartments, loginOfficer, registerOfficer } from '../api/complaintsApi.js';
import { useLanguage } from '../i18n/I18n.jsx';

export default function OfficerLogin() {
  const { t } = useLanguage(); const [registering, setRegistering] = useState(false); const [departments, setDepartments] = useState([]); const [form, setForm] = useState({ name: '', job_id: '', phone: '', password: '', department: '', job_id_document: null }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const navigate = useNavigate();
  useEffect(() => { getDepartments().then(({ data }) => { setDepartments(data); if (data[0]) setForm((current) => ({ ...current, department: String(data[0].id) })); }).catch(() => {}); }, []);
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { if (registering) { const data = new FormData(); Object.entries(form).forEach(([key, value]) => value && data.append(key, value)); const response = await registerOfficer(data); setMessage(response.data.message); setRegistering(false); } else { const response = await loginOfficer({ job_id: form.job_id, phone: form.phone, password: form.password }); localStorage.setItem('officerToken', response.data.token); localStorage.setItem('officerProfile', JSON.stringify(response.data.officer)); navigate('/officer-dashboard'); } } catch (requestError) { setError(requestError.response?.data?.error || t('invalidCredentials')); } };
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  return <main className="auth-page"><section className="auth-card"><div className="section-kicker">{t('officer').toUpperCase()}</div><h1>{registering ? t('register') : t('officerLogin')}</h1><p>{t('accessRestricted')}</p><form onSubmit={submit}>{registering && <label>{t('name')}<input name="name" value={form.name} onChange={update} required /></label>}<label>{t('jobId')}<input name="job_id" value={form.job_id} onChange={update} required /></label><label>{t('phone')}<input name="phone" value={form.phone} onChange={update} required /></label><label>{t('password')}<input type="password" name="password" value={form.password} onChange={update} minLength="8" required /></label>{registering && <><label>{t('department')}<select name="department" value={form.department} onChange={update} required>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select></label><label>{t('jobDocument')}<input type="file" name="job_id_document" accept="image/*,.pdf" onChange={(event) => setForm({ ...form, job_id_document: event.target.files[0] })} /></label></>}{error && <p className="error-message">{error}</p>}{message && <p className="message">{message}</p>}<button className="button primary-button">{registering ? t('register') : t('signIn')}</button></form><button className="text-button" onClick={() => setRegistering(!registering)}>{registering ? t('signIn') : t('register')}</button></section></main>;
}