import { query } from '../config/db.js';

export async function listUsers(req, res) { res.json((await query("SELECT id, name, email, role, created_at FROM users ORDER BY created_at DESC")).rows); }
export async function listOfficers(req, res) { res.json((await query('SELECT o.id, o.name, o.job_id, o.phone, o.department, o.verification_status, o.verification_document, d.name AS department_name FROM officers o JOIN departments d ON d.id = o.department ORDER BY o.name')).rows); }
export async function listDepartments(req, res) { res.json((await query('SELECT * FROM departments ORDER BY name')).rows); }
export async function createDepartment(req, res) { const { name, category_mapping = {} } = req.body; if (!name) return res.status(400).json({ error: 'name is required' }); res.status(201).json((await query('INSERT INTO departments (name, category_mapping) VALUES ($1, $2) RETURNING *', [name, category_mapping])).rows[0]); }
export async function assignOfficer(req, res) { const result = await query('UPDATE officers SET department = $1 WHERE id = $2 RETURNING id, name, job_id, phone, department, verification_status', [req.body.department, req.params.id]); if (!result.rows[0]) return res.status(404).json({ error: 'Officer not found' }); res.json(result.rows[0]); }
export async function reviewOfficer(req, res) { const { verification_status } = req.body; if (!['approved', 'rejected', 'pending'].includes(verification_status)) return res.status(400).json({ error: 'Invalid verification status' }); const result = await query('UPDATE officers SET verification_status = $1 WHERE id = $2 RETURNING id, name, job_id, phone, department, verification_status', [verification_status, req.params.id]); if (!result.rows[0]) return res.status(404).json({ error: 'Officer not found' }); res.json(result.rows[0]); }
export async function assignComplaint(req, res) { const result = await query('UPDATE complaints SET department_id = $1, status = CASE WHEN status = \'Reported\' THEN \'Assigned\' ELSE status END, updated_at = NOW() WHERE id = $2 RETURNING *', [req.body.department, req.params.id]); if (!result.rows[0]) return res.status(404).json({ error: 'Complaint not found' }); if (result.rows[0].status === 'Assigned') await query("INSERT INTO status_history (complaint_id, stage) VALUES ($1, 'Assigned')", [req.params.id]); res.json(result.rows[0]); }
export async function assignComplaintOfficer(req, res) { const result = await query('UPDATE complaints SET assigned_officer_id = $1, department_id = (SELECT department FROM officers WHERE id = $1), status = CASE WHEN status = \'Reported\' THEN \'Assigned\' ELSE status END, updated_at = NOW() WHERE id = $2 RETURNING *', [req.body.officer_id, req.params.id]); if (!result.rows[0]) return res.status(404).json({ error: 'Complaint or officer not found' }); res.json(result.rows[0]); }
export async function listAllComplaints(req, res) { res.json((await query('SELECT c.*, d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id = c.department_id ORDER BY c.created_at DESC')).rows); }